FROM influx6/php-alpine-base:0.1
MAINTAINER Ewetumo Alexander <trinoxf@gmail.com>

RUN \    
    # Add group and user for mysql
    apk update \
    && addgroup -S -g 500 mysql \
    && adduser -S -D -H -u 500 -G mysql -g "MySQL" mysql \
    # Create needed directories
    && mkdir -p /var/lib/mysql \
    && mkdir -p /run/mysqld \
    && mkdir -p /etc/mysql/conf.d \
    && mkdir -p /opt/mariadb/pre-init.d \
    && mkdir -p /opt/mariadb/post-init.d \
    && mkdir -p /opt/mariadb/pre-exec.d \
    # Set permissions
    && chown -R mysql:mysql /var/lib/mysql \
    && chown -R mysql:mysql /run/mysqld \
    && chmod -R 755 /opt/mariadb \
    && export CPU=`cat /proc/cpuinfo | grep -c processor` \
    # Add testing repo
    # && echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories \
    # Install packages
    && apk add --no-cache \
    # Install utils
    # pwgen openssl ca-certificates 
    # Installing needed libs
    # libstdc++ libaio gnutls ncurses-libs libcurl libxml2 boost proj geos \
    # Update CA certs
    # update-ca-certificates
    && apk add --no-cache mysql mysql-client \
    && rm -f /var/cache/apk/* \
    # Patching mysql_install_db: we don't have PAM plugin
    && sed -i 's/^.*auth_pam_tool_dir.*$/#auth_pam_tool_dir not exists/' /usr/bin/mysql_install_db \
    && mkdir -p /data/logs \
    && touch /data/logs/mysql-logs.index \
    && touch /data/logs/mysql-logs.bin \
    && chown -R mysql:mysql /data \
    && mkdir -p /etc/mysql

ENV DATADIR /data
ENV MYSQL_ROOT_HOST '%'
ENV MYSQL_ROOT_PASSWORD '12345'

# Copy mysql configuration to the etc folder.
COPY mariadb/mysql.cnf /etc/mysql/my.cnf

RUN chown -R mysql:mysql /etc/mysql

VOLUME /data/db/mysql

# Copy the mysql startup so we can run up the server.
COPY mariadb/bootsql /bin/bootsql
COPY mariadb/run.sh /bin/runsql
RUN chmod +x /bin/bootsql

# Add default port for mysql.
ENV MYSQL_PORT 3306

# Expose port for mysql usage.
EXPOSE 3306
