FROM influx6/alpine-base:0.1

ARG CLOUD_SDK_VERSION=232.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV PUBSUB_EMULATOR_HOST 0.0.0.0:8538

ENV PATH /google-cloud-sdk/bin:$PATH
RUN apk --update --no-cache add \
   python \
   py-crcmod \
   musl-dev \
   openssh-client \
   git \
   gnupg \
    && curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version

RUN mkdir -p /scripts
ADD google-pubsub-run.sh /scripts/google-pubsub-run.sh
RUN chmod -R +x /scripts
RUN rm -f /var/cache/apk/* /var/lib/apk/*

EXPOSE 8538

VOLUME ["/root/.config", "/data"]

