FROM php:7.4-fpm-alpine3.11

MAINTAINER Ewetumo Alexander <trinoxf@gmail.com>

# PORT is default port for apache
ENV PORT 80

# Persistent extensions dependencies
ARG EXTS="\
        bcmath \
        calendar \
        mbstring \
        exif \
        soap \
        zip \
        sysvsem \
        sysvshm \
        sysvmsg \
        shmop \
        sockets \
        bz2 \
        curl \
        simplexml \
        xml \
        opcache \
        tokenizer \
        ctype \
        session \
        fileinfo \
        iconv \
        json \
        posix \
        gd \
        mysqli \
        pdo \
        pdo_dblib \
        pdo_mysql \
        pdo_sqlite \
        pdo_pgsql \
        intl \
        dom \
        xmlwriter \
"

ARG RDEPS="\
        git \
        libgcc \
        icu-dev \
        curl-dev \
        libmcrypt-dev \
        libxml2-dev \
        freetds-dev \
        oniguruma-dev \
        postgresql-dev \
        openssl-dev \
        libpng-dev \
        libssh2-dev \
        sqlite-dev \
        libstdc++ \
        libzip-dev \
        make \
        bzip2-dev \
"

# Persistent runtime dependencies
ARG DEPS="\
        mysql-client \
        curl \
        icu \
        wget \
        bash \
        vim \
        unzip \
        libmcrypt \
        netcat-openbsd \
        msmtp \
        openssl \
        ca-certificates \
        composer \
        freetds \
        libpng \
        libssh2 \
        curl \
        freetype \
        libjpeg-turbo \
        php-soap \
        icu-libs \
        libltdl \
        libcurl \
        bzip2 \
        postgresql \
        libzip \
        sqlite \
"

ARG APP_ENV=prod

ENV APACHE_RUN_USER=www-data
ENV APACHE_RUN_GROUP=www-data
ENV APACHE_CONFDIR /etc/apache2
ENV APACHE_ENVVARS $APACHE_CONFDIR/envvars
ENV APACHE_LOG_DIR /var/www
ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi

STOPSIGNAL SIGQUIT

# When using Composer, disable the warning about running commands as root/super user
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY tags/apache /
COPY php/install-php-extensions /usr/local/bin/install-php-extensions
COPY php/etc/apache2 /etc/apache2
COPY php/apache-start /usr/local/bin/apache-start

RUN set -x \
    && chmod uga+x /usr/local/bin/install-php-extensions \ 
    && chmod uga+x /usr/local/bin/apache-start \
    && mkdir -p /etc/apache2 \
    && mkdir -p /etc/php/conf.d/ \
    && mkdir -p /var/logs \
    && mkdir -p /var/www/public \
    && mkdir -p /etc/apache2/sites-enabled \
    && mkdir -p /etc/apache2/conf-enabled \
    && ln -s /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf \
    && ln -s /etc/apache2/conf-available/server-cgi-bin.conf /etc/apache2/conf-enabled/server-cgi-bin.conf \
    && apk update \
    && apk add --no-cache $DEPS $RDEPS \
    && apk add --no-cache apache2-proxy \
    # && sed -i "s/LoadModule mpm_prefork_module modules\/mod_mpm_prefork.so/#LoadModule mpm_prefork_module modules\/mod_mpm_prefork.so/g" /etc/apache2/httpd.conf \
    # && sed -i "s/#LoadModule mpm_event_module modules\/mod_mpm_event.so/LoadModule mpm_event_module modules\/mod_mpm_event.so/g" /etc/apache2/httpd.conf \
    # && sed -i "s/#LoadModule rewrite_module modules\/mod_rewrite.so/#LoadModule rewrite_module modules\/mod_rewrite.so/g" /etc/apache2/httpd.conf \
    # && sed -i "s/#ServerName www.example.com:80/ServerName localhost/g" /etc/apache2/httpd.conf 
    && apk add --no-cache -u musl \
    && mkdir -p /run/apache2 \
    && docker-php-ext-install $EXTS \
    && docker-php-ext-enable $EXTS \
    && chown -R "$APACHE_RUN_USER:$APACHE_RUN_GROUP" /var/www \
    && rm -rf /var/lib/apt/lists/* \
    && apk del $RDEPS

RUN if [ ${APP_ENV} = "dev" ]; then \
        apk add --no-cache git openssh \
        && composer global require ext-mysqli \
        && composer global require hirak/prestissimo \
        && composer global require paragonie/random_compat \
        && composer global require mikey179/vfsStream \
        && composer global require phpunit/phpunit; \
    fi

COPY php/sites /var/www
EXPOSE 80

CMD ["/usr/local/bin/apache-start"]
