FROM influx6/alpine-base:0.1
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

RUN mkdir /scripts
ADD nats-streaming-setup.sh /scripts/nats-streaming-setup.sh
ADD gnats.conf /scripts/gnats.conf

# Expose client, management, and cluster ports
EXPOSE 4222 8222 6222

RUN /scripts/nats-streaming-setup.sh
