FROM anapsix/alpine-java
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

ENV  GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc \
        GLIBC_VERSION=2.28-r0 \
         LANG=C.UTF-8

RUN mkdir /scripts && \
	apk --no-cache add musl-dev libressl; \
	apk --no-cache  --virtual .build-deps add make librdkafka gcc python cyrus-sasl-dev lz4-dev build-base

ADD kafka-*.sh /scripts/
ADD kafka/server.properties /scripts/server.properties

RUN set -ex && sh /scripts/kafka-setup.sh
RUN apk del .build-deps && rm -f /var/cache/apk/*

