FROM anapsix/alpine-java
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

ENV  GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc \
        GLIBC_VERSION=2.28-r0 \
         LANG=C.UTF-8

RUN mkdir /scripts && \
	apk --no-cache add musl-dev libressl; \
	apk --no-cache  --virtual .build-deps add make librdkafka gcc python cyrus-sasl-dev lz4-dev build-base

ADD kafka-*.sh /scripts/

RUN set -ex && sh /scripts/kafka-librdkafka.sh 0.11.6
RUN set -ex && sh /scripts/kafka-setup.sh
RUN apk del .build-deps


