FROM influx6/debian-base:0.1
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

RUN mkdir /scripts && \
	apt update; \
	apt install -y make openjdk-8-jdk-headless libblkid1 libc6 libffi6 libgcc1 libglib2.0-dev \
	 libmount1 libpcre3 libselinux1 libuuid1 zlib1g libc-dev gcc libssl-dev

RUN rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

ADD kafka-*.sh /scripts/
ADD kafka/server.properties /scripts/server.properties

RUN set -ex &&  sh /scripts/kafka-librdkafka.sh 0.11.6
RUN set -ex &&  sh /scripts/kafka-setup.sh

