FROM influx6/debian-base:0.1
MAINTAINER Ewetumo Alexander <trinoxf@gmail.com>

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r mongodb && useradd -r -g mongodb mongodb

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		ca-certificates \
		gnupg dirmngr \
		jq curl \
		numactl \
		procps \
	&& rm -rf /var/lib/apt/lists/*

# grab gosu for easy step-down from root (https://github.com/tianon/gosu/releases)
ENV GOSU_VERSION 1.11
# grab "js-yaml" for parsing mongod's YAML config files (https://github.com/nodeca/js-yaml/releases)
ENV JSYAML_VERSION 3.10.0

RUN set -ex; \
	apt-get update; \
	apt-get install -y --no-install-recommends wget; \
	rm -rf /var/lib/apt/lists/*;

ADD ./gosu/* /usr/local/gosu/
RUN set -x; dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; cp /usr/local/gosu/gosu-$dpkgArch /usr/local/bin/gosu; rm -rf /usr/local/gosu

RUN chmod +x /usr/local/bin/gosu; gosu nobody true; \
	wget -O /js-yaml.js "https://github.com/nodeca/js-yaml/raw/${JSYAML_VERSION}/dist/js-yaml.js";

RUN mkdir /docker-entrypoint-initdb.d

# Allow build-time overrides (eg. to build image with MongoDB Enterprise version)
# Options for MONGO_PACKAGE: mongodb-org OR mongodb-enterprise
# Options for MONGO_REPO: repo.mongodb.org OR repo.mongodb.com
# Example: docker build --build-arg MONGO_PACKAGE=mongodb-enterprise --build-arg MONGO_REPO=repo.mongodb.com .
ARG MONGO_PACKAGE=mongodb-org
ARG MONGO_REPO=repo.mongodb.org
ENV MONGO_PACKAGE=${MONGO_PACKAGE} MONGO_REPO=${MONGO_REPO}

ENV MONGO_MAJOR 4.0
ENV MONGO_VERSION 4.0.4

RUN curl https://www.mongodb.org/static/pgp/server-$MONGO_MAJOR.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/$MONGO_MAJOR main" > /etc/apt/sources.list.d/mongodb-org-${MONGO_MAJOR}.list
# RUN echo "deb http://$MONGO_REPO/apt/debian stretch/${MONGO_PACKAGE%-unstable}/$MONGO_MAJOR main" | tee "/etc/apt/sources.list.d/${MONGO_PACKAGE%-unstable}.list"

RUN set -x \
	&& apt-get update \
	&& apt-get install -y  --allow-unauthenticated \
		${MONGO_PACKAGE}=$MONGO_VERSION \
		${MONGO_PACKAGE}-server=$MONGO_VERSION \
		${MONGO_PACKAGE}-shell=$MONGO_VERSION \
		${MONGO_PACKAGE}-mongos=$MONGO_VERSION \
		${MONGO_PACKAGE}-tools=$MONGO_VERSION \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/apt/archives/* \
	&& rm -rf /var/lib/mongodb \
	&& mv /etc/mongod.conf /etc/mongod.conf.orig

RUN mkdir -p /data/db/mongodb /data/db/mongodb/data /data/db/mongodb/configdb /data/db/mongodb/logs /etc/mongodb && \
	chown -R mongodb:mongodb /data/db/mongodb && chown -R mongodb:mongodb /etc/mongodb

VOLUME /data/db/mongodb/data /data/db/mongodb/configdb /data/db/mongodb/logs

COPY ./mongo/entrypoint.sh /usr/local/bin/

# Copy mongodb configuration to the etc folder.
COPY mongo/mongodb.cnf /etc/mongodb/mongodb.cnf
COPY mongo/db.js /data/db/mongodb/db.js

COPY ./mongo/bootmgo /bin/bootmgo
RUN chmod +x /bin/bootmgo

ENV MONGODB_PORT 27017
EXPOSE 27017 28017


