FROM influx6/debian-base:0.1

ARG CLOUD_SDK_VERSION=227.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV PUBSUB_EMULATOR_HOST 0.0.0.0:8538

ENV PATH /google-cloud-sdk/bin:$PATH
RUN apt update && apt install -y \
   python \
   python-crcmod  \
   openssh-client \
   gnupg \
    && curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version && \
    rm -rf /var/cache/apt/archives/* && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /scripts
ADD google-pubsub-run.sh /scripts/google-pubsub-run.sh
RUN chmod -R +x /scripts

EXPOSE 8538

VOLUME ["/root/.config", "/data"]
