FROM influx6/mariadb-debian-base:0.1

# set up nsswitch.conf for Go's "netgo" implementation
# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
# - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf

ARG VERSION=1.11.2

ADD golang-debian.sh /scripts/golang-setup.sh
RUN chmod +x /scripts/golang-setup.sh && /scripts/golang-setup.sh

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

