FROM influx6/debian-base:0.1
MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

ENV  GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc \
        GLIBC_VERSION=2.28-r0 \
         LANG=C.UTF-8

RUN mkdir /scripts && \
	apt update; \
	apt install -y make openjdk-8-jdk-headless libblkid1 libc6 libffi6 libgcc1 libglib2.0-dev \
	 libmount1 libpcre3 libselinux1 libuuid1 zlib1g libc-dev gcc

RUN rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

ADD kafka-*.sh /scripts/

RUN set -ex &&  sh /scripts/kafka-librdkafka.sh 0.11.6
RUN set -ex &&  sh /scripts/kafka-setup.sh


