#!/bin/sh

if [ -d /db/mysql ]; then
  echo "[i] MySQL directory already present, skipping creation"
else
  echo "[i] MySQL data directory not found, creating initial DBs $DATADIR"

  mysql_install_db --force --user=root --basedir=/usr/ --ldata="$DATADIR" > /dev/null

  if [ "$MYSQL_ROOT_PASSWORD" = "" ]; then
    MYSQL_ROOT_PASSWORD=123456
    echo "[i] MySQL root Password: $MYSQL_ROOT_PASSWORD"
  fi

  MYSQL_DATABASE=${MYSQL_DATABASE:-""}
  MYSQL_USER=${MYSQL_USER:-""}
  MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD:-""}

  if [ ! -d "/run/mysqld" ]; then
    mkdir -p /run/mysqld
  fi

  tfile=`mktemp`
  if [ ! -f "$tfile" ]; then
      return 1
  fi

  cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
EOF

  echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;" >> $tfile
  echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;" >> $tfile
  echo "SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${MYSQL_ROOT_PASSWORD}');" >> $tfile
  #echo "UPDATE user SET password=PASSWORD('') WHERE user='root' AND host='localhost';" >> $tfile
  echo "DROP DATABASE IF EXISTS test;" >> $tfile

  if [ "$MYSQL_USER" != "" ]; then
    echo "[i] Creating user: $MYSQL_USER with password $MYSQL_USER_PASSWORD"
    echo "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';" >> $tfile
    echo "CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_USER_PASSWORD';" >> $tfile
    echo "CREATE USER '$MYSQL_USER'@'::1' IDENTIFIED BY '$MYSQL_USER_PASSWORD';" >> $tfile
    # echo "UPDATE user SET password=PASSWORD('$MYSQL_USER_PASSWORD') WHERE user='$MYSQL_USER' AND host='localhost';" >> $tfile
    # echo "UPDATE user SET password=PASSWORD('$MYSQL_USER_PASSWORD') WHERE user='$MYSQL_USER' AND host='%';" >> $tfile
  fi


  if [ "$MYSQL_DATABASE" != "" ]; then
    echo "[i] Creating database: $MYSQL_DATABASE"
    echo "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile
    echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';" >> $tfile
    echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_USER_PASSWORD';" >> $tfile
  fi

  echo "[i] Executing tfile setup for MySQL as non-daemon"
  # /usr/bin/mysqld --user=root --bootstrap --verbose=0  --skip-name-resolve --skip-networking=0 < $tfile 
  /usr/bin/mysqld --user=root --bootstrap --verbose=1 < $tfile 


  rm -f $tfile
  echo "Done setting up mysql!"
fi

if [ "$fork" == "true" ]; then
    echo "[i] Running MySQL as daemon"
  /usr/share/mysql/mysql.server start $@
else 
  echo "[i] running mysql as non-daemon"
  echo "Starting mysql with $MYSQL_PORT with user=root in console mode ($@)"
  exec /usr/bin/mysqld --port "$MYSQL_PORT" --user=root --console $@
fi
