#!/usr/bin/env sh

sed -i "s/Listen 80/Listen ${PORT:-80}/g" /etc/apache2/ports.conf
sed -i "s/:80/:${PORT:-80}/g" /etc/apache2/sites-enabled/*

#boot up php-fpm
php-fpm -D

# apache2-foreground
httpd -D FOREGROUND
